FROM kyan/rails_legacy
MAINTAINER duncan@kyan.com
ENV REFRESHED_AT 2016-08-11

# Choose your ruby version
ENV RUBY_VERSION 'ruby 2.2'

# Install Ruby
RUN ruby-install --system $RUBY_VERSION

# Install RubyGems
RUN gem update --system --no-rdoc --no-ri

# Install Bundler
RUN gem install bundler --no-rdoc --no-ri

# Install gems
ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN bundle install
