default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: docker_demo_development
test:
  <<: *default
  database: docker_demo_test
production:
  <<: *default
  database: docker_demo_production
  username: docker_demo
  password: <%= ENV['DOCKER_DEMO_DATABASE_PASSWORD'] %>
